# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
import speech_recognition as sr
import os

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QFileDialog

class Ui_MainWindow(object):

    _data = ""
    # _filename = ""
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(323, 159)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnOpen = QtWidgets.QPushButton(self.centralwidget)
        self.btnOpen.setGeometry(QtCore.QRect(20, 10, 75, 24))
        self.btnOpen.setObjectName("btnOpen")
        self.btnOpen.clicked.connect(self.btnOpen_Click)
        self.lbl_audio = QtWidgets.QLabel(self.centralwidget)
        self.lbl_audio.setGeometry(QtCore.QRect(20, 50, 281, 14))
        self.lbl_audio.setObjectName("lbl_audio")
        self.btnRun = QtWidgets.QPushButton(self.centralwidget)
        self.btnRun.setGeometry(QtCore.QRect(20, 80, 75, 24))
        self.btnRun.setAutoDefault(False)
        self.btnRun.setObjectName("btnRun")
        self.btnRun.clicked.connect(self.btnRun_Click)
        self.btnRun.setEnabled(False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 323, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnOpen.setText(_translate("MainWindow", "Open & Run..."))
        self.lbl_audio.setText("...")
        self.btnRun.setText(_translate("MainWindow", "Save As..."))
        
    def btnOpen_Click(self):
        file, _ = QFileDialog.getOpenFileName(None, "Open Audio files", "","Sound Files (*.mp3 *.wav)")
        # file = QFileDialog.getOpenFileName(None, "Open Audio files", "","Sound Files (*.mp3 *.wav)").selectedFiles()
        audio = file.replace("/","\\\\")
        self.lbl_audio.setText("Converting audio file to text...")
        # print(audio)

        r = sr.Recognizer()
        with sr.AudioFile(audio) as source:
            r.adjust_for_ambient_noise(source)
            # print("Converting audio file to text...")
            sound = r.listen(source)
            try:
                global _data
                _data = r.recognize_google(sound,language="vi-VI")
            except Exception as ex:
                print(ex)

        self.lbl_audio.setText("Successfuly!")
        self.btnRun.setEnabled(True)
        # _setbtn = Ui_MainWindow.set_Enablebtn(self, True)
        # print("Successfuly!")

    def btnRun_Click(self):
        file, _ = QFileDialog.getSaveFileName(None,"Save As", "","Text Files (*.txt)")
        # print(file)
        global _data
        if _data != "":
            with open(file, mode = 'w', encoding = 'utf-8') as x_file:
                x_file.write(_data)
        
        
        self.lbl_audio.setText("Save As Successfuly!")
        self.btnOpen.setEnabled(True)
        self.btnRun.setEnabled(False)
        # _setbtn2 = Ui_MainWindow.set_Enablebtn(self, False)

    # def set_Enablebtn(self, default = True):
    #     self.btnOpen.setEnabled(not True)
    #     self.btnRun.setEnabled(not False)
        # msg = QMessageBox()
        # msg.setWindowTitle("Infomation!")
        # msg.setText("_data")
        # x = msg.exec_()
        # return


if __name__ == "__main__":

    sys.stdout.reconfigure(encoding='utf-8')
    sys.stdin.reconfigure(encoding='utf-8')
    sys.stderr.reconfigure(encoding='utf-8')

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())